AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  helloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda
      Handler: app.handler
      Runtime: python3.7
      Timeout: 30
      MemorySize: 256
      Events:
        MyEvent:
          Type: Api
          Properties:
            Path: /  #/hello
            Method: get
